# Generated by Django 3.0.7 on 2020-06-22 15:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=512, unique=True, verbose_name='주소')),
                ('birthday', models.DateField(verbose_name='생년월일')),
                ('phone', models.CharField(max_length=13, verbose_name='전화번호')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other'), ('None', 'None')], default='None', max_length=20, verbose_name='성별')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='회원')),
            ],
            options={
                'verbose_name': '회원 상세정보',
                'verbose_name_plural': '회원 상세정보 목록',
                'db_table': 'profiles',
            },
        ),
    ]
