# Generated by Django 3.0.7 on 2020-06-24 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-created_at'], 'verbose_name': '회원정보', 'verbose_name_plural': '회원목록'},
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
