# Generated by Django 3.0.7 on 2020-06-25 01:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200624_1053'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='user_profile', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
                ('nickname', models.CharField(max_length=64, verbose_name='별명')),
                ('bio', models.TextField(blank=True, max_length=512, null=True, verbose_name='자기소개')),
                ('address', models.CharField(blank=True, max_length=256, null=True, verbose_name='주소')),
                ('birthday', models.DateField(null=True, verbose_name='생일')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other'), ('None', 'None')], default='None', max_length=20, verbose_name='성별')),
                ('phone', models.CharField(blank=True, max_length=13, null=True, verbose_name='전화번호')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='추가일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='마지막 수정')),
            ],
            options={
                'verbose_name': '프로필',
                'verbose_name_plural': '프로필목록',
                'db_table': 'profiles',
                'ordering': ['user'],
            },
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', users.models.UserManager()),
            ],
        ),
    ]
