version: '3.1'

services:
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: api
    restart: always
    ports:
      - '8000:8000'
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_DB=${DATABASE_DB}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
    #command:
    #  - bash
    #  - -c
    #  - |
    #    ./wait-for-it.sh db:3306 -t 10;
    #    ./manage.py migrate;
    #    gunicorn --bind 0.0.0.0:8000 boilerplate.wsgi
    volumes:
      - .:/code
    depends_on:
      - db
  db:
    image: postgres:latest
    container_name: db
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PORT=${DATABASE_PORT}
      - POSTGRES_DB=${DATABASE_DB}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8
    volumes:
      - ${DATABASE_DATA_PATH}:/var/lib/postgresql/data/
